# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiArt < Formula
  desc ""
  homepage ""
  version "2.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5.4/ascii-art_Darwin_x86_64.tar.gz"
      sha256 "02a296cf595383f377ce0c977c220497e93c25996ab84ee98c5ea43e50e594f2"

      def install
        bin.install "ascii-art"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5.4/ascii-art_Darwin_arm64.tar.gz"
      sha256 "99af231c038953fc59d3abf804deb173bb2bd36d977154837ecffd0c4991a322"

      def install
        bin.install "ascii-art"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5.4/ascii-art_Linux_x86_64.tar.gz"
      sha256 "541746607c42f3ba322db344d57fb73ea526f3a983caf0f904b8bbd1539c7168"

      def install
        bin.install "ascii-art"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5.4/ascii-art_Linux_arm64.tar.gz"
      sha256 "fa7ee671eea0c943b699373b4904d2123e49090736f091fb234ccdf9a8df5783"

      def install
        bin.install "ascii-art"
      end
    end
  end
end
