# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciiArt < Formula
  desc ""
  homepage ""
  version "2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5/ascii-art_Darwin_x86_64.tar.gz"
      sha256 "b35d7d34f6eef9c5849bb4d5849874d3b18fbe0616141ec09843d2ace642c920"

      def install
        bin.install "ascii-art"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5/ascii-art_Darwin_arm64.tar.gz"
      sha256 "8684e3a13641e4a22bebaa529cb37c2dfa44bcab63a641c47ac7aa832242cb94"

      def install
        bin.install "ascii-art"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5/ascii-art_Linux_arm64.tar.gz"
      sha256 "3f19883d923619f35558577800da11b544415b5fd3950ee2dda76ed42a6ff518"

      def install
        bin.install "ascii-art"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/ascii-art/releases/download/v2.5/ascii-art_Linux_x86_64.tar.gz"
      sha256 "17c2f0b4c2fd898bae33f72c6a1ea30bad1558d3368a9d02f41b1a1b6864b4d1"

      def install
        bin.install "ascii-art"
      end
    end
  end
end
