# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliTutorial < Formula
  desc ""
  homepage ""
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.4/go-cli-tutorial_Darwin_x86_64.tar.gz"
      sha256 "1c4e1a4cbfd55de70f2e336b0d266d932ad1e30a3063c672e0b46516da94f65c"

      def install
        bin.install "go-cli-tutorial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.4/go-cli-tutorial_Darwin_arm64.tar.gz"
      sha256 "36778c4893883ed334c0b4ca66ed57ea6db5ecf752546de879b7a3ced8d51309"

      def install
        bin.install "go-cli-tutorial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.4/go-cli-tutorial_Linux_arm64.tar.gz"
      sha256 "1e66500dbcac43349c6b63e1aa722396aa57705fbdafcf9a43d49dde9a8ef418"

      def install
        bin.install "go-cli-tutorial"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.4/go-cli-tutorial_Linux_x86_64.tar.gz"
      sha256 "8bad413326b051cdf40d8942db7d279c8d9f63d293f5742503914e324891677a"

      def install
        bin.install "go-cli-tutorial"
      end
    end
  end
end
