# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliTutorial < Formula
  desc ""
  homepage ""
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.5/go-cli-tutorial_Darwin_amd64.tar.gz"
      sha256 "c7a17f95081b54cf9c01b57cc18478acc1aa43202df0f6dbc435fe19a2b8173a"

      def install
        bin.install "go-cli-tutorial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.5/go-cli-tutorial_Darwin_arm64.tar.gz"
      sha256 "2f5a1730a938ff9835a5489a4d1b6fd1a7a0679298808a113651822cc28fa3b9"

      def install
        bin.install "go-cli-tutorial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.5/go-cli-tutorial_Linux_amd64.tar.gz"
      sha256 "ab4539823e718afff3c96fd6001c2d5c093b86ed036d73c11b7a1373ae965dc1"

      def install
        bin.install "go-cli-tutorial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Minooo1/go-cli-tutorial/releases/download/v0.1.5/go-cli-tutorial_Linux_arm64.tar.gz"
      sha256 "62bf085aa1ded76ac22b698440eb3a836cf71c4ce6e78f40126f79febf056087"

      def install
        bin.install "go-cli-tutorial"
      end
    end
  end
end
