# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloCli < Formula
  desc ""
  homepage ""
  version "2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Minooo1/hello-cli/releases/download/v2.0/hello-cli_Darwin_arm64.tar.gz"
      sha256 "7df2c850140fe89484da4f4f038162260bbd2c39d94b09f95270d9260c43b641"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/hello-cli/releases/download/v2.0/hello-cli_Darwin_x86_64.tar.gz"
      sha256 "7a68d49d8745e38c9b77b2a2b723b6da7bcaea4b4f5851ae9e478404cde48831"

      def install
        bin.install "hello-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Minooo1/hello-cli/releases/download/v2.0/hello-cli_Linux_arm64.tar.gz"
      sha256 "91c125a330e8197c04303e22fee4bdc0bc2d910b41f70165b686be0f7f9e42d2"

      def install
        bin.install "hello-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Minooo1/hello-cli/releases/download/v2.0/hello-cli_Linux_x86_64.tar.gz"
      sha256 "ea3d551020aed6bf6852b0552e5bd8068ad002435838702cfd96667a3c730716"

      def install
        bin.install "hello-cli"
      end
    end
  end
end
